### ISSUE TITLE
Неправильный подсчет доходности SHA

### ISSUE THREAD

**Issue by Maximkin** [mhthnz/hashfair-chrome#1]
При включенном расширении прогноз доходности по SHA выше чем при выключенном. Похоже коммуналка прибавляется вместо того чтобы отниматься
![2017-08-08 15 55 30](https://user-images.githubusercontent.com/28284691/29058417-90e22392-7c53-11e7-9828-f1d1c16fe57a.png)
![2017-08-08 15 54 58](https://user-images.githubusercontent.com/28284691/29058441-a833d414-7c53-11e7-9897-27f6193bb6b9.png)

**Comment by mhthnz** [comment]
исправлено.
